Repository shedding-hub/shedding-hub, pull requests merged in 2024-11, with the labels that each got.

#56 Add data from Han et al. (2020).
  .gitignore
  data/han2020sequential/han2020sequential.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: stool

#58 Add data for Ke et al. (2022)
  data/.schema.yaml
  data/ke2022daily/41564_2022_1105_MOESM4_ESM.xlsx
  data/ke2022daily/illustration_adjustment.png
  data/ke2022daily/ke2022daily-extraction.md
  data/ke2022daily/ke2022daily.yaml
  data/ke2022daily/symptom_date_gap.csv
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: nasal swab, 🧪 specimen: saliva

#69 Add data from The COVID-19 Investigation Team (2020)
  data/team2020clinical/CombinedDataset.xlsx
  data/team2020clinical/team2020clinical-extraction.md
  data/team2020clinical/team2020clinical.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: nasopharyngeal swab

#62 Lavezzo2020suppression
  data/lavezzo2020suppression/anonymised_data_public_final.xlsx
  data/lavezzo2020suppression/lavezzo2020suppression-extraction.md
  data/lavezzo2020suppression/lavezzo2020suppression.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: nasopharyngeal swab, 🧪 specimen: oropharyngeal swab

#67 Extract data from Han et al. (2020).
  data/han2020sequential/han2020sequential-extraction.md
  data/han2020sequential/han2020sequential.yaml
  data/han2020sequential/mother-data.png
  data/han2020sequential/mother_project.json
  data/han2020sequential/neonate-data.png
  data/han2020sequential/neonate_project.json
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: stool, 🧪 specimen: sputum, 🧪 specimen: nasopharyngeal swab, 🧪 specimen: saliva, 🧪 specimen: oropharyngeal swab, 🧪 specimen: urine
