Repository shedding-hub/shedding-hub, pull requests merged in 2024-09, with the labels that each got.

#19 Create dataset for Arts et al. (2023)
  .github/workflows/summarize.py
  data/.schema.yaml
  data/Arts2023Longitudinal.yaml
Labels: 🔎 marker: SARS-CoV-2, 🔎 marker: crAssphage, 🔎 marker: PMMoV, 🧪 specimen: stool

#27 Automatically verify naming convention for data files.
  tests/test_data.py
Labels: enhancement

#25 Add data from Kim 2020 viral
  data/.schema.yaml
  data/kim2020viral/kim2020viral.yaml
  tests/examples/valid_multiple_analytes.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: sputum, 🧪 specimen: nasopharyngeal swab

#30 Update 'Contributing' section to comply with new folder structure.
  README.md
Labels: documentation

#29 Remote min, median, and max in GitHub workflow comment.
  .github/workflows/summarize.py
  .github/workflows/summarize.yaml
  tests/test_summarize.py
Labels: enhancement

#28 Ensure limits are positive.
  data/.schema.yaml
Labels: bug

#35 Create shrestha2020distribution.yaml
  data/shrestha2020distribution/shrestha2020distribution.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: nasopharyngeal swab
