Repository shedding-hub/shedding-hub, pull requests merged in 2024-10, with the labels that each got.

#38 Add data from Fajnzylber2020SARS
  data/.schema.yaml
  data/fajnzylber2020sars/41467_2020_19057_MOESM3_ESM.xlsx
  data/fajnzylber2020sars/fajnzylber2020sars-extraction.md
  data/fajnzylber2020sars/fajnzylber2020sars.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: sputum, 🧪 specimen: nasopharyngeal swab, 🧪 specimen: nasal swab

#40 Shrestha2020distribution branch
  data/arts2023longitudinal/arts2023longitudinal-extraction.md
  data/arts2023longitudinal/arts2023longitudinal.yaml
  data/arts2023longitudinal/msphere.00132-23-s0002.xlsx
  data/kim2020viral/jkms-35-e86-s004.xls
  data/kim2020viral/kim2020viral-extraction.md
  data/kim2020viral/kim2020viral.xlsx
  data/shrestha2020distribution/CombinedDataset.xlsx
  data/shrestha2020distribution/shrestha2020distribution-extraction.md
  data/shrestha2020distribution/shrestha2020distribution.yaml
Labels: documentation, 🔎 marker: SARS-CoV-2

#45 Add extraction sheet and raw data for Kim and Arts dataset
  data/arts2023longitudinal/arts2023longitudinal-extraction.md
  requirements.in
  requirements.txt
Labels: documentation

#39 Add two datasets used in Goyal et al. (2020)
  data/lescure2020clinical/Viral_Loads.csv
  data/lescure2020clinical/lescure2020clinical-extraction.md
  data/lescure2020clinical/lescure2020clinical.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: nasopharyngeal swab

#54 Add Young2020epidemiologic
  data/young2020epidemiologic/CombinedDataset.xlsx
  data/young2020epidemiologic/Goyal_linreg.png
  data/young2020epidemiologic/Viral_Loads.csv
  data/young2020epidemiologic/young2020epidemiologic-extraction.md
  data/young2020epidemiologic/young2020epidemiologic.yaml
  requirements.in
  requirements.txt
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: nasopharyngeal swab
