Repository shedding-hub/shedding-hub, pull requests merged in 2024-08, with the labels that each got.

#1 Add extraction tutorial and fix missing data in Wölfel et al. (2020) dataset.
  .gitignore
  data/woelfel2020.yaml
  requirements.in
  requirements.txt
  tutorials/woelfel2020-extraction.md
Labels: bug, enhancement

#4 Add 'Contributing' section to `README.md`.
  README.md
Labels: documentation, enhancement

#13 Expand analyte metadata.
  data/.schema.yaml
  data/woelfel2020.yaml
  tests/examples/valid_multiple_analytes.yaml
  tests/examples/valid_single_analyte.yaml
Labels: enhancement, schema

#15 Add trigger to build shedding-hub.github.io.
  .github/workflows/build.yml
Labels: documentation, enhancement

#10 Create dataset for Liu et al. (2024).
  data/.schema.yaml
  data/Liu2024Longitudinal.yaml
Labels: documentation, 🔎 marker: SARS-CoV-2, 🔎 marker: PMMoV, 🔎 marker: human mtDNA, 🧪 specimen: stool

#9 Add Human Metadata to woelfel2020.yaml
  data/woelfel2020.yaml
Labels: enhancement

#16 Only deploy GitHub Pages from `main` branch.
  .github/workflows/build.yml
Labels: bug

#11 Add data from Natarajan et al. (2022) and utility functions.
  data/.schema.yaml
  data/natarajan2022.yaml
  pyproject.toml
  requirements.in
  requirements.txt
  shedding_hub/__init__.py
  shedding_hub/util.py
  tests/test_data.py
  tests/test_util.py
  tutorials/natarajan2022-extraction.md
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: stool

#20 Adding more demographic information and extraction markdown file for Liu2024
  data/.schema.yaml
  data/Liu2024Longitudinal.yaml
  tutorials/Liu2024Longitudinal-extraction.md
Labels: documentation, 🔎 marker: SARS-CoV-2, 🔎 marker: PMMoV, 🔎 marker: human mtDNA, 🧪 specimen: stool

#21 Add data from Lui et al. (2020).
  data/.schema.yaml
  data/lui2020viral.yaml
Labels: 🔎 marker: SARS-CoV-2, 🧪 specimen: stool
